hostname r1
password zebra
!
interface eth1
 description to_r2
 ip address 10.12.1.0/31
 ip ospf network point-to-point
 ip ospf area 0.0.0.0
!
interface eth2
 description to_r3
 ip address 10.13.1.0/31
 ip ospf network point-to-point
 ip ospf area 0.0.0.0
!
interface eth3
 description to_host1
 ip address 192.168.1.1/24
 ip ospf area 0.0.0.0
!
interface lo
 ip address 1.1.1.1/32
 ip ospf area 0.0.0.0
!
router ospf
 ospf router-id 1.1.1.1
 passive-interface eth3
 passive-interface lo
!
line vty
!
