hostname r4
password zebra
!
interface eth1
 description to_r2
 ip address 10.24.1.1/31
 ip ospf network point-to-point
 ip ospf area 0.0.0.0
!
interface eth2
 description to_r3
 ip address 10.34.1.1/31
 ip ospf network point-to-point
 ip ospf area 0.0.0.0
!
interface eth3
 description to_host2
 ip address 192.168.2.1/24
 ip ospf area 0.0.0.0
!
interface lo
 ip address 4.4.4.4/32
 ip ospf area 0.0.0.0
!
router ospf
 ospf router-id 4.4.4.4
 passive-interface eth3
 passive-interface lo
!
line vty
!
